from __future__ import annotations
import collections.abc
import pyspiel
import typing
__all__: list[str] = ['ActionType', 'BlackjackGame', 'BlackjackState', 'DEALER_TURN', 'HIDDEN_CARD_STR', 'HIT', 'INITIAL_DEAL', 'PLAYER_TURN', 'Phase', 'STAND', 'card_to_string', 'cards_to_strings', 'get_card_by_string', 'phase_to_string']
class ActionType:
    """
    Members:
    
      HIT
    
      STAND
    """
    HIT: typing.ClassVar[ActionType]  # value = <ActionType.HIT: 0>
    STAND: typing.ClassVar[ActionType]  # value = <ActionType.STAND: 1>
    __members__: typing.ClassVar[dict[str, ActionType]]  # value = {'HIT': <ActionType.HIT: 0>, 'STAND': <ActionType.STAND: 1>}
    @typing.overload
    def __eq__(self, other: ActionType) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: ActionType) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class BlackjackGame(pyspiel.Game):
    def __getstate__(self) -> str:
        ...
    def __setstate__(self, arg0: str) -> None:
        ...
class BlackjackState(pyspiel.State):
    def __getstate__(self) -> str:
        ...
    def __setstate__(self, arg0: str) -> None:
        ...
    def cards(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> list[int]:
        ...
    def dealer_id(self) -> int:
        ...
    def dealers_visible_card(self) -> int:
        ...
    def get_best_player_total(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def is_turn_over(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def phase(self) -> Phase:
        ...
    def player_cards_sorted_vector(self) -> list[int]:
        ...
    def visible_cards_sorted_vector(self) -> list[int]:
        ...
class Phase:
    """
    Members:
    
      INITIAL_DEAL
    
      PLAYER_TURN
    
      DEALER_TURN
    """
    DEALER_TURN: typing.ClassVar[Phase]  # value = <Phase.DEALER_TURN: 2>
    INITIAL_DEAL: typing.ClassVar[Phase]  # value = <Phase.INITIAL_DEAL: 0>
    PLAYER_TURN: typing.ClassVar[Phase]  # value = <Phase.PLAYER_TURN: 1>
    __members__: typing.ClassVar[dict[str, Phase]]  # value = {'INITIAL_DEAL': <Phase.INITIAL_DEAL: 0>, 'PLAYER_TURN': <Phase.PLAYER_TURN: 1>, 'DEALER_TURN': <Phase.DEALER_TURN: 2>}
    @typing.overload
    def __eq__(self, other: Phase) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: Phase) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
def card_to_string(arg0: typing.SupportsInt | typing.SupportsIndex) -> str:
    ...
def cards_to_strings(cards: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], start_index: typing.SupportsInt | typing.SupportsIndex = 0) -> list[str]:
    ...
def get_card_by_string(arg0: str) -> int:
    ...
def phase_to_string(arg0: Phase) -> str:
    ...
DEALER_TURN: Phase  # value = <Phase.DEALER_TURN: 2>
HIDDEN_CARD_STR: str = '??'
HIT: ActionType  # value = <ActionType.HIT: 0>
INITIAL_DEAL: Phase  # value = <Phase.INITIAL_DEAL: 0>
PLAYER_TURN: Phase  # value = <Phase.PLAYER_TURN: 1>
STAND: ActionType  # value = <ActionType.STAND: 1>
