from __future__ import annotations
import pyspiel
import typing
__all__: list[str] = ['ACROSS', 'Clue', 'CrosswordActionStruct', 'CrosswordActionStructSampler', 'CrosswordBoard', 'DOWN', 'Direction', 'clue_id']
class Clue:
    @property
    def description(self) -> str:
        ...
    @property
    def direction(self) -> Direction:
        ...
    @property
    def number(self) -> int:
        ...
class CrosswordActionStruct(pyspiel.ActionStruct):
    @staticmethod
    @typing.overload
    def __init__(*args, **kwargs) -> None:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: dict) -> None:
        ...
    @typing.overload
    def __init__(self, json_str: str) -> None:
        ...
    @typing.overload
    def __init__(self, clue_id: str, word: str) -> None:
        ...
    def __str__(self) -> str:
        ...
    def to_string(self) -> str:
        ...
    @property
    def clue_id(self) -> str:
        ...
    @property
    def word(self) -> str:
        ...
class CrosswordActionStructSampler(pyspiel.ActionStructSampler):
    def __init__(self, arg0: pyspiel.State, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def sample_action_struct(self) -> pyspiel.ActionStruct:
        ...
class CrosswordBoard:
    def answer(self, arg0: str) -> str:
        ...
    def clue(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> Clue:
        ...
    def to_string(self) -> str:
        ...
class Direction:
    """
    Members:
    
      ACROSS
    
      DOWN
    """
    ACROSS: typing.ClassVar[Direction]  # value = <Direction.ACROSS: 0>
    DOWN: typing.ClassVar[Direction]  # value = <Direction.DOWN: 1>
    __members__: typing.ClassVar[dict[str, Direction]]  # value = {'ACROSS': <Direction.ACROSS: 0>, 'DOWN': <Direction.DOWN: 1>}
    @typing.overload
    def __eq__(self, other: Direction) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: Direction) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
def clue_id(clue: Clue) -> str:
    ...
ACROSS: Direction  # value = <Direction.ACROSS: 0>
DOWN: Direction  # value = <Direction.DOWN: 1>
