from __future__ import annotations
import collections.abc
import pyspiel
import typing
__all__: list[str] = ['DEAL', 'DEFAULT_GIN_BONUS', 'DEFAULT_HAND_SIZE', 'DEFAULT_KNOCK_CARD', 'DEFAULT_NUM_CARDS', 'DEFAULT_NUM_RANKS', 'DEFAULT_NUM_SUITS', 'DEFAULT_UNDERCUT_BONUS', 'DISCARD', 'DRAW', 'DRAW_STOCK_ACTION', 'DRAW_UPCARD_ACTION', 'FIRST_UPCARD', 'GAME_OVER', 'GinRummyObservationStruct', 'GinRummyState', 'GinRummyStateStruct', 'GinRummyUtils', 'KNOCK', 'KNOCK_ACTION', 'LAYOFF', 'MAX_NUM_DRAW_UPCARD_ACTIONS', 'MAX_POSSIBLE_DEADWOOD', 'MELD_ACTION_BASE', 'NUM_DISTINCT_ACTIONS', 'NUM_MELD_ACTIONS', 'NUM_PLAYERS', 'OBSERVATION_TENSOR_SIZE', 'PASS_ACTION', 'Phase', 'WALL', 'WALL_STOCK_SIZE']
class GinRummyObservationStruct(pyspiel.ObservationStruct):
    current_player: str
    finished_layoffs: bool
    phase: str
    prev_upcard: str | None
    upcard: str | None
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str) -> None:
        ...
    @property
    def deadwood(self) -> list[int]:
        ...
    @deadwood.setter
    def deadwood(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def discard_pile(self) -> list[str]:
        ...
    @discard_pile.setter
    def discard_pile(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def hands(self) -> list[list[str]]:
        ...
    @hands.setter
    def hands(self, arg0: collections.abc.Sequence[collections.abc.Sequence[str]]) -> None:
        ...
    @property
    def knock_card(self) -> int:
        ...
    @knock_card.setter
    def knock_card(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def knocked(self) -> list[bool]:
        ...
    @knocked.setter
    def knocked(self, arg0: collections.abc.Sequence[bool]) -> None:
        ...
    @property
    def layed_melds(self) -> list[list[list[str]]]:
        ...
    @layed_melds.setter
    def layed_melds(self, arg0: collections.abc.Sequence[collections.abc.Sequence[collections.abc.Sequence[str]]]) -> None:
        ...
    @property
    def layoffs(self) -> list[str]:
        ...
    @layoffs.setter
    def layoffs(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def observing_player(self) -> int:
        ...
    @observing_player.setter
    def observing_player(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def pass_on_first_upcard(self) -> list[bool]:
        ...
    @pass_on_first_upcard.setter
    def pass_on_first_upcard(self, arg0: collections.abc.Sequence[bool]) -> None:
        ...
    @property
    def stock_size(self) -> int:
        ...
    @stock_size.setter
    def stock_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class GinRummyState(pyspiel.State):
    def __getstate__(self) -> str:
        ...
    def __setstate__(self, arg0: str) -> None:
        ...
    def current_phase(self) -> Phase:
        ...
    def current_player(self) -> int:
        ...
    def deadwood(self) -> list[int]:
        ...
    def discard_pile(self) -> list[int]:
        ...
    def finished_layoffs(self) -> bool:
        ...
    def hands(self) -> list[list[int]]:
        ...
    def knock_card(self) -> int | None:
        ...
    def knocked(self) -> list[bool]:
        ...
    def known_cards(self) -> list[list[int]]:
        ...
    def layed_melds(self) -> list[list[int]]:
        ...
    def layoffs(self) -> list[int]:
        ...
    def pass_on_first_upcard(self) -> list[bool]:
        ...
    def prev_upcard(self) -> int | None:
        ...
    def stock_size(self) -> int:
        ...
    def to_observation_struct(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> pyspiel.ObservationStruct:
        ...
    def to_struct(self) -> pyspiel.StateStruct:
        ...
    def upcard(self) -> int | None:
        ...
class GinRummyStateStruct(pyspiel.StateStruct):
    current_player: str
    finished_layoffs: bool
    phase: str
    prev_upcard: str | None
    upcard: str | None
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str) -> None:
        ...
    @property
    def deadwood(self) -> list[int]:
        ...
    @deadwood.setter
    def deadwood(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def discard_pile(self) -> list[str]:
        ...
    @discard_pile.setter
    def discard_pile(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def hands(self) -> list[list[str]]:
        ...
    @hands.setter
    def hands(self, arg0: collections.abc.Sequence[collections.abc.Sequence[str]]) -> None:
        ...
    @property
    def knock_card(self) -> int:
        ...
    @knock_card.setter
    def knock_card(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def knocked(self) -> list[bool]:
        ...
    @knocked.setter
    def knocked(self, arg0: collections.abc.Sequence[bool]) -> None:
        ...
    @property
    def layed_melds(self) -> list[list[list[str]]]:
        ...
    @layed_melds.setter
    def layed_melds(self, arg0: collections.abc.Sequence[collections.abc.Sequence[collections.abc.Sequence[str]]]) -> None:
        ...
    @property
    def layoffs(self) -> list[str]:
        ...
    @layoffs.setter
    def layoffs(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def pass_on_first_upcard(self) -> list[bool]:
        ...
    @pass_on_first_upcard.setter
    def pass_on_first_upcard(self, arg0: collections.abc.Sequence[bool]) -> None:
        ...
    @property
    def stock_size(self) -> int:
        ...
    @stock_size.setter
    def stock_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class GinRummyUtils:
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def all_layoffs(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[int]:
        ...
    def all_meld_groups(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[list[list[int]]]:
        ...
    def all_melds(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[list[int]]:
        ...
    def best_meld_group(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[list[int]]:
        ...
    def card_int(self, arg0: str) -> int:
        ...
    def card_ints_to_card_strings(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[str]:
        ...
    def card_rank(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def card_string(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> str:
        ...
    def card_strings_to_card_ints(self, arg0: collections.abc.Sequence[str]) -> list[int]:
        ...
    def card_suit(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def card_value(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def hand_to_string(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> str:
        ...
    def is_consecutive(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> bool:
        ...
    def is_rank_meld(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> bool:
        ...
    def is_suit_meld(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> bool:
        ...
    def legal_discards(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: typing.SupportsInt | typing.SupportsIndex) -> list[int]:
        ...
    def legal_melds(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: typing.SupportsInt | typing.SupportsIndex) -> list[int]:
        ...
    def meld_to_int(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> int:
        ...
    @typing.overload
    def min_deadwood(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: typing.SupportsInt | typing.SupportsIndex | None) -> int:
        ...
    @typing.overload
    def min_deadwood(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> int:
        ...
    def rank_meld_layoff(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> int:
        ...
    def rank_melds(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[list[int]]:
        ...
    def suit_meld_layoffs(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[int]:
        ...
    def suit_melds(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[list[int]]:
        ...
    @typing.overload
    def total_card_value(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> int:
        ...
    @typing.overload
    def total_card_value(self, arg0: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]]) -> int:
        ...
    @property
    def int_to_meld(self) -> dict[int, list[int]]:
        ...
class Phase:
    """
    Members:
    
      DEAL
    
      FIRST_UPCARD
    
      DRAW
    
      DISCARD
    
      KNOCK
    
      LAYOFF
    
      WALL
    
      GAME_OVER
    """
    DEAL: typing.ClassVar[Phase]  # value = <Phase.DEAL: 0>
    DISCARD: typing.ClassVar[Phase]  # value = <Phase.DISCARD: 3>
    DRAW: typing.ClassVar[Phase]  # value = <Phase.DRAW: 2>
    FIRST_UPCARD: typing.ClassVar[Phase]  # value = <Phase.FIRST_UPCARD: 1>
    GAME_OVER: typing.ClassVar[Phase]  # value = <Phase.GAME_OVER: 7>
    KNOCK: typing.ClassVar[Phase]  # value = <Phase.KNOCK: 4>
    LAYOFF: typing.ClassVar[Phase]  # value = <Phase.LAYOFF: 5>
    WALL: typing.ClassVar[Phase]  # value = <Phase.WALL: 6>
    __members__: typing.ClassVar[dict[str, Phase]]  # value = {'DEAL': <Phase.DEAL: 0>, 'FIRST_UPCARD': <Phase.FIRST_UPCARD: 1>, 'DRAW': <Phase.DRAW: 2>, 'DISCARD': <Phase.DISCARD: 3>, 'KNOCK': <Phase.KNOCK: 4>, 'LAYOFF': <Phase.LAYOFF: 5>, 'WALL': <Phase.WALL: 6>, 'GAME_OVER': <Phase.GAME_OVER: 7>}
    @typing.overload
    def __eq__(self, other: Phase) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: Phase) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
DEAL: Phase  # value = <Phase.DEAL: 0>
DEFAULT_GIN_BONUS: int = 25
DEFAULT_HAND_SIZE: int = 10
DEFAULT_KNOCK_CARD: int = 10
DEFAULT_NUM_CARDS: int = 52
DEFAULT_NUM_RANKS: int = 13
DEFAULT_NUM_SUITS: int = 4
DEFAULT_UNDERCUT_BONUS: int = 25
DISCARD: Phase  # value = <Phase.DISCARD: 3>
DRAW: Phase  # value = <Phase.DRAW: 2>
DRAW_STOCK_ACTION: int = 53
DRAW_UPCARD_ACTION: int = 52
FIRST_UPCARD: Phase  # value = <Phase.FIRST_UPCARD: 1>
GAME_OVER: Phase  # value = <Phase.GAME_OVER: 7>
KNOCK: Phase  # value = <Phase.KNOCK: 4>
KNOCK_ACTION: int = 55
LAYOFF: Phase  # value = <Phase.LAYOFF: 5>
MAX_NUM_DRAW_UPCARD_ACTIONS: int = 50
MAX_POSSIBLE_DEADWOOD: int = 98
MELD_ACTION_BASE: int = 56
NUM_DISTINCT_ACTIONS: int = 241
NUM_MELD_ACTIONS: int = 185
NUM_PLAYERS: int = 2
OBSERVATION_TENSOR_SIZE: int = 644
PASS_ACTION: int = 54
WALL: Phase  # value = <Phase.WALL: 6>
WALL_STOCK_SIZE: int = 2
