from __future__ import annotations
import collections.abc
import pyspiel
import typing
__all__: list[str] = ['Card', 'HungarianTarokkAnnouncementState', 'HungarianTarokkBid', 'HungarianTarokkBiddingState', 'HungarianTarokkBonus', 'HungarianTarokkBonusAnnouncement', 'HungarianTarokkCalledCard', 'HungarianTarokkGame', 'HungarianTarokkObservationStruct', 'HungarianTarokkPhase', 'HungarianTarokkSide', 'HungarianTarokkState']
class Card:
    def __eq__(self, arg0: Card) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, index: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def is_tarokk(self) -> bool:
        ...
    def points(self) -> int:
        ...
    def suit(self) -> int:
        ...
    @property
    def index(self) -> int:
        ...
    @index.setter
    def index(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class HungarianTarokkAnnouncementState:
    def __str__(self) -> str:
        ...
    def bonus_announced(self, bonus: HungarianTarokkBonus, side: HungarianTarokkSide) -> bool:
        ...
    def bonus_kontra_level(self, bonus: HungarianTarokkBonus, side: HungarianTarokkSide) -> int:
        ...
    def called_card_tarokk(self) -> Card:
        ...
    def current_player(self) -> int:
        ...
    def declared_tarokks(self, player: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def game_kontra_level(self) -> int:
        ...
    def hivatalbol_kontra_player(self) -> int:
        ...
    def is_finished(self) -> bool:
        ...
    def legal_actions(self) -> list[int]:
        ...
    def partner(self) -> int:
        ...
    def public_side(self, player: typing.SupportsInt | typing.SupportsIndex) -> typing.Any:
        ...
    def to_string(self) -> str:
        ...
class HungarianTarokkBid:
    """
    Members:
    
      THREE
    
      TWO
    
      ONE
    
      SOLO
    """
    ONE: typing.ClassVar[HungarianTarokkBid]  # value = <HungarianTarokkBid.ONE: 2>
    SOLO: typing.ClassVar[HungarianTarokkBid]  # value = <HungarianTarokkBid.SOLO: 3>
    THREE: typing.ClassVar[HungarianTarokkBid]  # value = <HungarianTarokkBid.THREE: 0>
    TWO: typing.ClassVar[HungarianTarokkBid]  # value = <HungarianTarokkBid.TWO: 1>
    __members__: typing.ClassVar[dict[str, HungarianTarokkBid]]  # value = {'THREE': <HungarianTarokkBid.THREE: 0>, 'TWO': <HungarianTarokkBid.TWO: 1>, 'ONE': <HungarianTarokkBid.ONE: 2>, 'SOLO': <HungarianTarokkBid.SOLO: 3>}
    @typing.overload
    def __eq__(self, other: HungarianTarokkBid) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: HungarianTarokkBid) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class HungarianTarokkBiddingState:
    def __str__(self) -> str:
        ...
    def cue_bidder(self) -> int:
        ...
    def cued_card(self) -> HungarianTarokkCalledCard:
        ...
    def current_player(self) -> int:
        ...
    def declarer(self) -> int:
        ...
    def is_finished(self) -> bool:
        ...
    def legal_actions(self) -> list[int]:
        ...
    def num_bidders(self) -> int:
        ...
    def obligatory_called_card(self) -> HungarianTarokkCalledCard:
        ...
    def pagat_ulti_obligation(self) -> bool:
        ...
    def passed_out(self) -> bool:
        ...
    def player_bid(self, player: typing.SupportsInt | typing.SupportsIndex) -> typing.Any:
        ...
    def standing_bid(self) -> typing.Any:
        ...
    def to_string(self) -> str:
        ...
    def winning_bid(self) -> HungarianTarokkBid:
        ...
    def yielded(self) -> bool:
        ...
class HungarianTarokkBonus:
    """
    Members:
    
      TRULL
    
      FOUR_KINGS
    
      PAGAT_ULTI
    
      XXI_CATCH
    
      DOUBLE_GAME
    
      VOLAT
    """
    DOUBLE_GAME: typing.ClassVar[HungarianTarokkBonus]  # value = <HungarianTarokkBonus.DOUBLE_GAME: 4>
    FOUR_KINGS: typing.ClassVar[HungarianTarokkBonus]  # value = <HungarianTarokkBonus.FOUR_KINGS: 1>
    PAGAT_ULTI: typing.ClassVar[HungarianTarokkBonus]  # value = <HungarianTarokkBonus.PAGAT_ULTI: 2>
    TRULL: typing.ClassVar[HungarianTarokkBonus]  # value = <HungarianTarokkBonus.TRULL: 0>
    VOLAT: typing.ClassVar[HungarianTarokkBonus]  # value = <HungarianTarokkBonus.VOLAT: 5>
    XXI_CATCH: typing.ClassVar[HungarianTarokkBonus]  # value = <HungarianTarokkBonus.XXI_CATCH: 3>
    __members__: typing.ClassVar[dict[str, HungarianTarokkBonus]]  # value = {'TRULL': <HungarianTarokkBonus.TRULL: 0>, 'FOUR_KINGS': <HungarianTarokkBonus.FOUR_KINGS: 1>, 'PAGAT_ULTI': <HungarianTarokkBonus.PAGAT_ULTI: 2>, 'XXI_CATCH': <HungarianTarokkBonus.XXI_CATCH: 3>, 'DOUBLE_GAME': <HungarianTarokkBonus.DOUBLE_GAME: 4>, 'VOLAT': <HungarianTarokkBonus.VOLAT: 5>}
    @typing.overload
    def __eq__(self, other: HungarianTarokkBonus) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: HungarianTarokkBonus) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class HungarianTarokkBonusAnnouncement:
    bonus: str
    side: str
    def __init__(self) -> None:
        ...
    @property
    def kontra_level(self) -> int:
        ...
    @kontra_level.setter
    def kontra_level(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class HungarianTarokkCalledCard:
    """
    Members:
    
      NONE
    
      XIX
    
      XVIII
    
      XX
    """
    NONE: typing.ClassVar[HungarianTarokkCalledCard]  # value = <HungarianTarokkCalledCard.NONE: 0>
    XIX: typing.ClassVar[HungarianTarokkCalledCard]  # value = <HungarianTarokkCalledCard.XIX: 1>
    XVIII: typing.ClassVar[HungarianTarokkCalledCard]  # value = <HungarianTarokkCalledCard.XVIII: 2>
    XX: typing.ClassVar[HungarianTarokkCalledCard]  # value = <HungarianTarokkCalledCard.XX: 3>
    __members__: typing.ClassVar[dict[str, HungarianTarokkCalledCard]]  # value = {'NONE': <HungarianTarokkCalledCard.NONE: 0>, 'XIX': <HungarianTarokkCalledCard.XIX: 1>, 'XVIII': <HungarianTarokkCalledCard.XVIII: 2>, 'XX': <HungarianTarokkCalledCard.XX: 3>}
    @typing.overload
    def __eq__(self, other: HungarianTarokkCalledCard) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: HungarianTarokkCalledCard) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class HungarianTarokkGame(pyspiel.Game):
    ObservationStruct = HungarianTarokkObservationStruct
    def __getstate__(self) -> str:
        ...
    def __setstate__(self, arg0: str) -> None:
        ...
class HungarianTarokkObservationStruct(pyspiel.ObservationStruct):
    bid: str | None
    called_tarokk: str | None
    obligatory_call: str
    phase: str
    @staticmethod
    @typing.overload
    def __init__(*args, **kwargs) -> None:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: dict) -> None:
        ...
    @property
    def bid_slots(self) -> list[int]:
        ...
    @bid_slots.setter
    def bid_slots(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def bonus_announcements(self) -> list[HungarianTarokkBonusAnnouncement]:
        ...
    @bonus_announcements.setter
    def bonus_announcements(self, arg0: collections.abc.Sequence[HungarianTarokkBonusAnnouncement]) -> None:
        ...
    @property
    def current_player(self) -> int:
        ...
    @current_player.setter
    def current_player(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def current_trick(self) -> list[str | None]:
        ...
    @current_trick.setter
    def current_trick(self, arg0: collections.abc.Sequence[str | None]) -> None:
        ...
    @property
    def current_trick_leader(self) -> int:
        ...
    @current_trick_leader.setter
    def current_trick_leader(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def declared_tarokks(self) -> list[int]:
        ...
    @declared_tarokks.setter
    def declared_tarokks(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def declarer(self) -> int:
        ...
    @declarer.setter
    def declarer(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def declarer_shown_tarokks(self) -> list[str]:
        ...
    @declarer_shown_tarokks.setter
    def declarer_shown_tarokks(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def discard_tarokk_counts(self) -> list[int]:
        ...
    @discard_tarokk_counts.setter
    def discard_tarokk_counts(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def game_kontra(self) -> int:
        ...
    @game_kontra.setter
    def game_kontra(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def hand(self) -> list[str]:
        ...
    @hand.setter
    def hand(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def hivatalbol_kontra(self) -> int:
        ...
    @hivatalbol_kontra.setter
    def hivatalbol_kontra(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def last_trick(self) -> list[str | None]:
        ...
    @last_trick.setter
    def last_trick(self, arg0: collections.abc.Sequence[str | None]) -> None:
        ...
    @property
    def observing_player(self) -> int:
        ...
    @observing_player.setter
    def observing_player(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def sides(self) -> list[str]:
        ...
    @sides.setter
    def sides(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
class HungarianTarokkPhase:
    """
    Members:
    
      DEALING
    
      BIDDING
    
      TALON_EXCHANGE
    
      ANNOUNCEMENTS
    
      PLAYING
    
      FINISHED
    """
    ANNOUNCEMENTS: typing.ClassVar[HungarianTarokkPhase]  # value = <HungarianTarokkPhase.ANNOUNCEMENTS: 3>
    BIDDING: typing.ClassVar[HungarianTarokkPhase]  # value = <HungarianTarokkPhase.BIDDING: 1>
    DEALING: typing.ClassVar[HungarianTarokkPhase]  # value = <HungarianTarokkPhase.DEALING: 0>
    FINISHED: typing.ClassVar[HungarianTarokkPhase]  # value = <HungarianTarokkPhase.FINISHED: 5>
    PLAYING: typing.ClassVar[HungarianTarokkPhase]  # value = <HungarianTarokkPhase.PLAYING: 4>
    TALON_EXCHANGE: typing.ClassVar[HungarianTarokkPhase]  # value = <HungarianTarokkPhase.TALON_EXCHANGE: 2>
    __members__: typing.ClassVar[dict[str, HungarianTarokkPhase]]  # value = {'DEALING': <HungarianTarokkPhase.DEALING: 0>, 'BIDDING': <HungarianTarokkPhase.BIDDING: 1>, 'TALON_EXCHANGE': <HungarianTarokkPhase.TALON_EXCHANGE: 2>, 'ANNOUNCEMENTS': <HungarianTarokkPhase.ANNOUNCEMENTS: 3>, 'PLAYING': <HungarianTarokkPhase.PLAYING: 4>, 'FINISHED': <HungarianTarokkPhase.FINISHED: 5>}
    @typing.overload
    def __eq__(self, other: HungarianTarokkPhase) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: HungarianTarokkPhase) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class HungarianTarokkSide:
    """
    Members:
    
      DECLARERS
    
      DEFENDERS
    """
    DECLARERS: typing.ClassVar[HungarianTarokkSide]  # value = <HungarianTarokkSide.DECLARERS: 0>
    DEFENDERS: typing.ClassVar[HungarianTarokkSide]  # value = <HungarianTarokkSide.DEFENDERS: 1>
    __members__: typing.ClassVar[dict[str, HungarianTarokkSide]]  # value = {'DECLARERS': <HungarianTarokkSide.DECLARERS: 0>, 'DEFENDERS': <HungarianTarokkSide.DEFENDERS: 1>}
    @typing.overload
    def __eq__(self, other: HungarianTarokkSide) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: HungarianTarokkSide) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class HungarianTarokkState(pyspiel.State):
    def __getstate__(self) -> str:
        ...
    def __setstate__(self, arg0: str) -> None:
        ...
    def announcements(self) -> HungarianTarokkAnnouncementState:
        ...
    def bidding(self) -> HungarianTarokkBiddingState:
        ...
    def current_phase(self) -> HungarianTarokkPhase:
        ...
    def declarer(self) -> int:
        ...
    def is_annulled(self) -> bool:
        ...
    def partner(self) -> int:
        ...
    def player_cards(self, player: typing.SupportsInt | typing.SupportsIndex) -> list[Card]:
        ...
    def talon(self) -> list[Card]:
        ...
    def winning_bid(self) -> HungarianTarokkBid:
        ...
