from __future__ import annotations
import collections.abc
import pyspiel
import typing
__all__: list[str] = ['ActionType', 'CALL', 'FOLD', 'INVALID_CARD', 'LeducState', 'RAISE']
class ActionType:
    """
    Members:
    
      FOLD
    
      CALL
    
      RAISE
    """
    CALL: typing.ClassVar[ActionType]  # value = <ActionType.CALL: 1>
    FOLD: typing.ClassVar[ActionType]  # value = <ActionType.FOLD: 0>
    RAISE: typing.ClassVar[ActionType]  # value = <ActionType.RAISE: 2>
    __members__: typing.ClassVar[dict[str, ActionType]]  # value = {'FOLD': <ActionType.FOLD: 0>, 'CALL': <ActionType.CALL: 1>, 'RAISE': <ActionType.RAISE: 2>}
    @typing.overload
    def __eq__(self, other: ActionType) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: ActionType) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class LeducState(pyspiel.State):
    def __getstate__(self) -> str:
        ...
    def __setstate__(self, arg0: str) -> None:
        ...
    def get_private_cards(self) -> list[int]:
        ...
    def money(self) -> list[float]:
        ...
    def pot(self) -> int:
        ...
    def private_card(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def public_card(self) -> int:
        ...
    def round(self) -> int:
        ...
    def round1(self) -> list[int]:
        ...
    def round2(self) -> list[int]:
        ...
    def set_private_cards(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
CALL: ActionType  # value = <ActionType.CALL: 1>
FOLD: ActionType  # value = <ActionType.FOLD: 0>
INVALID_CARD: int = -10000
RAISE: ActionType  # value = <ActionType.RAISE: 2>
