from __future__ import annotations
import collections.abc
import pyspiel
import typing
__all__: list[str] = ['PokerkitStateStruct']
class PokerkitStateStruct(pyspiel.StateStruct):
    betting_history: str
    is_terminal: bool
    def __init__(self) -> None:
        ...
    def to_json_base(self) -> ...:
        ...
    @property
    def bets(self) -> list[int]:
        ...
    @bets.setter
    def bets(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def blinds(self) -> list[int]:
        ...
    @blinds.setter
    def blinds(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def board_cards(self) -> list[int]:
        ...
    @board_cards.setter
    def board_cards(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def burn_cards(self) -> list[int]:
        ...
    @burn_cards.setter
    def burn_cards(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def current_player(self) -> int:
        ...
    @current_player.setter
    def current_player(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def hole_cards(self) -> list[list[int]]:
        ...
    @hole_cards.setter
    def hole_cards(self, arg0: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]]) -> None:
        ...
    @property
    def legal_actions(self) -> list[int]:
        ...
    @legal_actions.setter
    def legal_actions(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def mucked_cards(self) -> list[int]:
        ...
    @mucked_cards.setter
    def mucked_cards(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def observation(self) -> list[str]:
        ...
    @observation.setter
    def observation(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def per_player_acpc_logs(self) -> list[list[list[str]]]:
        ...
    @per_player_acpc_logs.setter
    def per_player_acpc_logs(self, arg0: collections.abc.Sequence[collections.abc.Sequence[collections.abc.Sequence[str]]]) -> None:
        ...
    @property
    def per_player_phh_actions(self) -> list[list[str]]:
        ...
    @per_player_phh_actions.setter
    def per_player_phh_actions(self, arg0: collections.abc.Sequence[collections.abc.Sequence[str]]) -> None:
        ...
    @property
    def player_contributions(self) -> list[int]:
        ...
    @player_contributions.setter
    def player_contributions(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def pot_size(self) -> int:
        ...
    @pot_size.setter
    def pot_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def pots(self) -> list[int]:
        ...
    @pots.setter
    def pots(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def stacks(self) -> list[int]:
        ...
    @stacks.setter
    def stacks(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def starting_stacks(self) -> list[int]:
        ...
    @starting_stacks.setter
    def starting_stacks(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
