defaults:
  - /model/tarokk@model: small
  - _self_

seed: 0
num_iterations: 1
exploration: 0.3
device: "cuda"

sampler:
  advantage_capacity: 1_000_000
  strategy_capacity: 1_000_000
  num_traversals: 1000

training:
  lr: 1e-3

data:
  advantage:
    train_split: 0.9
    batch_size: 256
    workers: 4
  strategy:
    train_split: 0.9
    batch_size: 256
    workers: 4
