defaults:
  - /model/tarokk@model: small
  - _self_

seed: 42
num_iterations: 1
exploration: 0.3

sampler:
  advantage_capacity: 10_000
  strategy_capacity: 10_000
  num_traversals: 20_000
  batch_size: 4096
  device: "cuda"

training:
  lr: 1e-3

data:
  advantage:
    train_split: 0.9
    batch_size: 256
    workers: 4
  strategy:
    train_split: 0.9
    batch_size: 256
    workers: 4
