import pyspiel.hungarian_tarokk as T

NUM_PLAYERS = 4
# Each player plays exactly one card per trick.
CARDS_PER_TRICK = NUM_PLAYERS

NUM_BID_SLOTS = 7

MAX_HAND_SIZE = 12
MAX_ANNOUNCEMENTS_LENGTH = 12
MAX_NUM_TRICKS = 9

ANNOUNCEMENTS_FIRST_ACTION = T.AnnouncementActions.CALL_ACTION_BASE
ANNOUNCEMENTS_LAST_ACTION = T.AnnouncementActions.LAST_ACTION
ANNOUNCEMENTS_NUM_ACTIONS = ANNOUNCEMENTS_LAST_ACTION - ANNOUNCEMENTS_FIRST_ACTION + 1